# Generated by Django 4.2.7 on 2024-04-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0003_allee_client_controle_emplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
