# Generated by Django 4.2.7 on 2024-04-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0004_alter_marque_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
